In [1]:
import numpy

ModuleNotFoundError: No module named 'numpy'

In [2]:
pip install numpy

                                              0.0/12.9 MB ? eta -:--:--
                                              0.1/12.9 MB 1.6 MB/s eta 0:00:09
     -                                        0.5/12.9 MB 6.7 MB/s eta 0:00:02
     -                                        0.5/12.9 MB 6.7 MB/s eta 0:00:02
     --                                       0.8/12.9 MB 4.8 MB/s eta 0:00:03
     -----                                    1.8/12.9 MB 8.1 MB/s eta 0:00:02
     -----                                    1.8/12.9 MB 8.1 MB/s eta 0:00:02
     ------                                   2.2/12.9 MB 6.9 MB/s eta 0:00:02
     --------                                 2.7/12.9 MB 7.4 MB/s eta 0:00:02
     --------                                 2.7/12.9 MB 7.4 MB/s eta 0:00:02
     ---------                                3.1/12.9 MB 6.8 MB/s eta 0:00:02
     -----------                              3.6/12.9 MB 7.1 MB/s eta 0:00:02
     -----------                              3.7/12.9 MB 7

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
alist = [1,2,3,4,5,6,7]

In [4]:
print(alist)

[1, 2, 3, 4, 5, 6, 7]


In [5]:
print(type(alist))

<class 'list'>


In [6]:
ar1 = np.array(alist)

NameError: name 'np' is not defined

In [7]:
import numpy as np


In [8]:
ar1 = np.array(alist)

In [9]:
print(ar1)

[1 2 3 4 5 6 7]


In [10]:
print(type(ar1))

<class 'numpy.ndarray'>


In [11]:
1 ar1.dtype

SyntaxError: invalid syntax (901492773.py, line 1)

In [12]:
ar1.dtype

dtype('int64')

In [16]:
ar2 = np.array([1.1,2.2,3.3])

In [17]:
ar2

array([1.1, 2.2, 3.3])

In [18]:
ar2.dtype

dtype('float64')

In [19]:
list_data = [1, 2., 3]

ar3 = np.array(list_data)

print(ar3)


[1. 2. 3.]


In [20]:
arr1 = np.array([1,2,3.,4])

print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1. 2. 3. 4.]
1
(4,)


In [21]:
arr2 = np.array([1,2,3.,4], [5,6,7,8],[9,10,11,12])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [22]:
arr2 = np.array([[1,2,3.,4], [5,6,7,8],[9,10,11,12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
2
(3, 4)


In [23]:
arr3 = arr2.reshape(-1,3)

print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
2
(4, 3)


In [ ]:
arr4 = arr2.reshape(2,5)

print(arr4)
print(arr4.ndim)
print(arr4.shape)

In [24]:
arr4= arr2.reshape(2,-1,3)

print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
3
(2, 2, 3)


In [ ]:
from time import process_time

tot = 0

start = process_time()


for i in range(10000001): tot += 1

end = process_time()

print('time=',(end-start), tot)

time= 0.421875 10000001


In [27]:
alist = np.array([1,2,3.,4,5])
blist = np.array([6,7,8,9,10])


In [31]:
from time import process_time

start = process_time()

x = np.arange(1, 100001)
y = np.arange(100001,200001)
z = np.zeros_like(x)

for i in range(100000) :
    z[i] = x[i] + y[i]
    
end = process_time()

print('time=',(end-start),z)



time= 0.015625 [100002 100004 100006 ... 299996 299998 300000]


In [32]:
from time import process_time

start = process_time()

x = np.arange(1, 100001)
y = np.arange(100001,200001)
z = np.zeros_like(x)

z = x + y 
    
end = process_time()

print('time=',(end-start),z)



time= 0.0 [100002 100004 100006 ... 299996 299998 300000]


In [33]:
data = [0,1,2,3,4,5,6,7,8,9]

for i in range data

SyntaxError: invalid syntax (3742139669.py, line 3)

In [34]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
result = []

for i in data:
    result.append(i * 2)

print(result)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [35]:
a = np.array([1,2,3])
b = np.array([10,20,30])

2 * a + b

array([12, 24, 36])

In [36]:
a == 2

array([False,  True, False])

In [37]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4


In [41]:
a = np.array([[0,1,2],[3,4,5]])
print(a[1,1])

4


In [42]:
print(a[0,0])
print(a[1,3])

0


IndexError: index 3 is out of bounds for axis 1 with size 3

In [43]:
print(a[0,0])
print(a[1,2])

0
5


In [44]:
a = np.array([0,1,2,3],[4,5,6,7])
a

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [45]:
a = np.array([0,1,2,3],[4,5,6,7])

result = a[:, 1]
print(result)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [46]:
a = np.array([[0,1,2,3],[4,5,6,7]])

result = a[:, 1]
print(result)

[1 5]


In [48]:
a = np.array([[0,1,2,3],[4,5,6,7]])

result = a[1,2]

print(result)

6


In [50]:
a = np.array([[0,1,2,3],[4,5,6,7]])

result = a[1,1:4]

print(result)

[5 6 7]


In [52]:
a = np.array([[0,1,2,3],[4,5,6,7]])

result = a[0:2, 0:2]

print(result)

[[0 1]
 [4 5]]


In [54]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True,
False, True, False, True, False])

a[idx]

array([0, 2, 4, 6, 8])

In [57]:
a == 1

array([False,  True, False, False, False, False, False, False, False,
       False])

In [62]:
a % 2


array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [63]:

a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

# 팬시 인덱싱(fancy indexing) - 조건문 연산을 사용하여 짝수인 원소만 골라내기

In [64]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

a[a%2 == 0]

array([0, 2, 4, 6, 8])

In [65]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
b = np.array([0,2,4,6,8])

In [66]:
a[[0,2,4,6,8]]

array([11, 33, 55, 77, 99])

In [67]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [68]:
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [70]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(a[1,4])

IndexError: index 4 is out of bounds for axis 1 with size 4

In [72]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result = a[:, [0, 3]]
print(result)


[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [74]:
result = a[1,1:2]

print(result)

[6]


In [75]:
result = a[1, [1, 2]]
print(result)  # [6 7]

[6 7]


In [76]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [77]:
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [78]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
11, 12, 13, 14, 15, 16, 17, 18, 19,20])

# 1.배열에서 3의배수찾기
# 2.배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아주세요.
# 3.배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아주세요.

In [81]:
result = x[x % 3 == 0]
print(result)

[ 3  6  9 12 15 18]


In [82]:
result2 = x[(x % 3 == 0) & (x % 4 == 1)]
print("#2. 3으로 나누어지고, 4로 나누면 나머지가 1인 수:", result2)

#2. 3으로 나누어지고, 4로 나누면 나머지가 1인 수: [9]


In [84]:
result3 = x[(x % 3 == 0) & (x % 4 == 1)]
print("#3. (반복) 3으로 나누어지고, 4로 나누면 나머지가 1인 수:", result3)

#3. (반복) 3으로 나누어지고, 4로 나누면 나머지가 1인 수: [9]


In [85]:
%pip install pandas

                                              0.0/11.6 MB ? eta -:--:--
                                              0.2/11.6 MB 6.9 MB/s eta 0:00:02
     --                                       0.8/11.6 MB 10.8 MB/s eta 0:00:02
     -----                                    1.5/11.6 MB 12.2 MB/s eta 0:00:01
     --------                                 2.4/11.6 MB 14.3 MB/s eta 0:00:01
     ----------                               3.1/11.6 MB 14.2 MB/s eta 0:00:01
     ------------                             3.6/11.6 MB 13.4 MB/s eta 0:00:01
     ---------------                          4.6/11.6 MB 14.8 MB/s eta 0:00:01
     ------------------                       5.5/11.6 MB 15.2 MB/s eta 0:00:01
     ---------------------                    6.2/11.6 MB 15.9 MB/s eta 0:00:01
     ------------------------                 7.2/11.6 MB 15.9 MB/s eta 0:00:01
     ----------------------------             8.3/11.6 MB 16.6 MB/s eta 0:00:01
     --------------------------------         9.3


[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [86]:
import pandas as pd

In [87]:
pd.__version__

'2.2.3'

In [90]:
df = pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+10
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [91]:
df.describe()

나이           키            재산
count   7.000000    7.000000  5.000000e+00
mean   34.000000  189.857143  2.578000e+09
std    13.466007   35.983462  5.003441e+09
min    18.000000  170.000000  6.000000e+02
25%    26.000000  172.000000  5.000000e+07
50%    32.000000  177.000000  3.400000e+08
75%    39.000000  184.000000  1.000000e+09
max    58.000000  270.000000  1.150000e+10

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [93]:
df.tail()

이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09
5   캡틴마블  25    파일럿     미국  170  3.400000e+08
6  블랙위도우  32    스파이    러시아  170  5.000000e+07

In [94]:
df.head()

이름  나이     직업     국적    키            재산
0   아이언맨  58    CEO     미국  174  1.150000e+10
1     토르  45      신  아스가르드  190           NaN
2  스파이더맨  18   고등학생     미국  177  6.000000e+02
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270  1.000000e+09

In [95]:
pd.options.display.float_format = '{:.0f}'.format
 

In [96]:
df.describe()

나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [97]:
df.head()

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [98]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [100]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [101]:
df.nlargest(2,'나이')

이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [102]:
df.nlargest(3,'키')

이름  나이     직업     국적    키         재산
4    헐크  33  핵물리학자     미국  270 1000000000
1    토르  45      신  아스가르드  190        NaN
3  원더우먼  27     공주  데미스키라  178        NaN

In [103]:
df.nsmallest('재산')

TypeError: DataFrame.nsmallest() missing 1 required positional argument: 'columns'

In [104]:
df['재산'].nsmallest

<bound method Series.nsmallest of 0   11500000000
1           NaN
2           600
3           NaN
4    1000000000
5     340000000
6      50000000
Name: 재산, dtype: float64>

In [105]:
df(0:2)

SyntaxError: invalid syntax (2163416602.py, line 1)

In [106]:
df[0:2]

이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [107]:
df.iloc[:5,:3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [108]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [110]:
df2 = df.copy()

In [111]:
df2

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [112]:
df2.index = ['a','b','c','d','e','f','g']
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [113]:
df2['a':'d']

이름  나이    직업     국적    키          재산
a   아이언맨  58   CEO     미국  174 11500000000
b     토르  45     신  아스가르드  190         NaN
c  스파이더맨  18  고등학생     미국  177         600
d   원더우먼  27    공주  데미스키라  178         NaN

In [114]:
df2[0:3]

이름  나이    직업     국적    키          재산
a   아이언맨  58   CEO     미국  174 11500000000
b     토르  45     신  아스가르드  190         NaN
c  스파이더맨  18  고등학생     미국  177         600

In [115]:
df2.loc['a','b']

KeyError: 'b'

In [116]:
df2.loc['a':'b']

이름  나이   직업     국적    키          재산
a  아이언맨  58  CEO     미국  174 11500000000
b    토르  45    신  아스가르드  190         NaN

In [117]:
df2.loc['a','이름']

'아이언맨'

In [118]:
df2.loc['a':'b','이름':'직업']

이름  나이   직업
a  아이언맨  58  CEO
b    토르  45    신

In [119]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [120]:
df.loc['2':'6','이름':'국적']

이름  나이     직업     국적
2  스파이더맨  18   고등학생     미국
3   원더우먼  27     공주  데미스키라
4     헐크  33  핵물리학자     미국
5   캡틴마블  25    파일럿     미국
6  블랙위도우  32    스파이    러시아

In [121]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [125]:
df[':2'>30 & ':2'<50]

TypeError: unsupported operand type(s) for &: 'int' and 'str'

In [126]:
df['나이'>30]

TypeError: '>' not supported between instances of 'str' and 'int'

In [127]:
df['나이'] >30

0     True
1     True
2    False
3    False
4     True
5    False
6     True
Name: 나이, dtype: bool

In [130]:
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000